on:
  #push:
  #  branches:
  #  - master
  #workflow_dispatch:
jobs:
  check_sync:
    name: Check latest upload to homepage
    runs-on: ubuntu-22.04
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
      with: 
        fetch-depth: 0
    - name: Fetch status and badge
      run: |-
        bash sync-check.sh
    - name: Commit badge
      run: |-
        git diff
        git config user.email "badge-bot@example.com"
        git config user.name "Badge-bot"
        git diff --quiet || (git add badge.svg && git commit -m "Update badge")
        git push
